import type { UserSettings } from "./types.js";

export const DEFAULT_RAW_CAPTURE_ENDPOINT = "https://riftreplay.com/api/v1/replays";

/** Fresh device defaults; callers can safely update nested preferences. */
export function createDefaultSettings(): UserSettings {
  return {
    username: "",
    firstRunComplete: false,
    lastSeenVersion: "",
    defaultGamePlatform: "tcga",
    homeDeckThemeEnabled: false,
    syncMode: "community-and-hubs",
    communitySyncEnabled: true,
    firebaseUid: "",
    firebaseRefreshToken: "",
    firebaseCredentialGeneration: "",
    accountUid: "",
    accountEmail: "",
    accountHandle: "",
    accountDisplayName: "",
    accountProfilePublic: false,
    accountLastVerifiedAt: "",
    accountLastVerificationError: "",
    accountCloudSyncEnabled: false,
    accountCloudSyncLastSyncedAt: "",
    accountCloudSyncLastRestoredAt: "",
    accountCloudSyncDeviceId: "",
    accountCloudSyncDeviceName: "",
    accountCloudSyncRemoteGenerationId: "",
    accountCloudSyncLastError: "",
    anonymousDiagnosticsEnabled: true,
    anonymousInstallId: "",
    anonymousInstallCreatedAt: "",
    anonymousUsageLastHeartbeatAt: "",
    anonymousUsageLastHeartbeatVersion: "",
    enhancedInsightsEnabled: false,
    enhancedInsightsIntroSeen: false,
    enhancedInsightsPostGamePromptEnabled: true,
    debugMode: false,
    confirmationEnabled: true,
    replayCaptureEnabled: true,
    replayKeyframesEnabled: true,
    replayFramePreset: "standard",
    replayVideoEnabled: true,
    replayVideoMode: "game-frame",
    replayVideoQuality: "sharp",
    replayMicAudioEnabled: false,
    replayCustomFlagTypes: ["Mistake Consequence", "Question", "Alternative Line"],
    replayFolders: [],
    replayShadowClipEnabled: false,
    replayShadowClipSeconds: 60,
    replayShadowClipHotkey: "CommandOrControl+Shift+C",
    replayShadowClipHotkeyEnabled: true,
    replayQuickFlagHotkey: "CommandOrControl+Shift+F",
    replayQuickFlagHotkeyEnabled: true,
    rawCapture: {
      enabled: false,
      webReplayAutoUploadEnabled: false,
      webReplayAutoUploadAccountUid: "",
      tcgaWebReplayAutoUploadEnabled: false,
      tcgaWebReplayAutoUploadAccountUid: "",
      webReplayDiscordShareEnabled: false,
      webReplayDiscordShareAccountUid: "",
      webReplayDiscordShareHubIds: [],
      uploadEnabled: false,
      endpoint: DEFAULT_RAW_CAPTURE_ENDPOINT,
      apiKey: "",
      visibility: "private"
    },
    deckTrackerEnabled: false,
    deckTrackerAutoStart: false,
    deckTrackerSaveToReplay: false,
    deckTrackerPerformanceMode: "balanced",
    deckTrackerPinnedCards: {},
    matchupPrepWidgetEnabled: true,
    microphoneDeviceId: "",
    gameZoomFactor: 1,
    autoSaveAfterSeconds: 45,
    overlaySessionStartedAt: "",
    overlayDisplay: {
      profile: "grind",
      showBranding: true,
      showWebsite: true,
      showSession: true,
      showLatestMatch: true,
      showResult: true,
      showOpponentName: true,
      showScore: true,
      showPlatform: true,
      showDeck: true,
      showLegendWinRate: true,
      showMatchupWinRate: true,
      showActiveDeckStats: false,
      showDeckSessionStats: true,
      showDeckMatchups: true,
      showFooter: true
    },
    screenshotDirectory: "",
    replayDirectory: "",
    screenshotHotkey: "F9",
    screenshotHotkeyEnabled: true,
    scorepadDeviceId: "",
    scorepadDeviceSecret: "",
    scorepadLinkedAt: "",
    activeDeckId: "",
    activeHubs: [],
    privateHubWebReplayGrantKeys: [],
    activeTeams: []
  };
}
